version: '3.8'

services:
  web:
    image: my-php-app
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db  # db - это имя контейнера PostgreSQL
      - DB_USER=postgres
      - DB_PASSWORD=123
      - DB_NAME=library_system
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: library_system
      LANG: en_US.UTF-8   # Указываем кодировку UTF-8
    networks:
      - mynetwork

networks:
  mynetwork:  # Сеть для взаимодействия контейнеров
